name: Build & Publish Spaceport

on:
  workflow_call:
    inputs:
      publish_spaceport:
        type: boolean
        description: If true, publishes the spaceport after building (otherwise just build)
        default: false
      clear_cache:
        type: boolean
        description: If true, clears the cache before running
        default: false
    secrets:
      spacemaven_user:
        description: Your Spacemaven username to publish as
        required: true
      spacemaven_key:
        description: Your Spacemaven key to publish with
        required: true

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    name: Clear the cache if requested
    # It breaks sometimes when the plugins update
    # TODO figure this out for real
    if: ${{ inputs.clear_cache }}
    permissions:
      actions: write
    steps:
      - name: Clear cache
        uses: actions/github-script@v6
        with:
          # https://stackoverflow.com/questions/63521430/clear-cache-in-github-actions
          script: |
            console.log("About to clear")
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            
            for (const cache of caches.data.actions_caches) {
              console.log(cache)
              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }
            
            console.log("Clear completed")
  build-and-publish:
    needs: clear-cache
    if: always()
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            tasks: publishLinuxTargetsToSpacemavenNativeRepository
            cc: cc
            cxx: c++
          - os: windows-latest
            tasks: publishWindowsTargetsToSpacemavenNativeRepository
            cc: cl
            cxx: cl
          - os: macos-latest
            tasks: publishMacosTargetsToSpacemavenNativeRepository
            cc: cc
            cxx: c++
    name: Build and Publish
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: on-failure
          add-job-summary-as-pr-comment: on-failure
          validate-wrappers: true
          cache-write-only: ${{ inputs.clear_cache || false }}
      - name: Setup Publishing Properties
        run: |
          echo "spacemaven.user=${{ secrets.spacemaven_user }}" >> gradle.properties
          echo "spacemaven.key=${{ secrets.spacemaven_key }}" >> gradle.properties
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1.4.1
        if: matrix.os == 'windows-latest'
      - name: Build Project
        run: ./gradlew build
      - name: Publish Project
        if: ${{ inputs.publish_spaceport }}
        run: ./gradlew ${{ matrix.tasks }}
  finalize-publish:
    needs: build-and-publish
    name: Finalize Publication
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: on-failure
          add-job-summary-as-pr-comment: on-failure
          validate-wrappers: true
      - name: Setup Publishing Properties
        run: |
          echo "spacemaven.user=${{ secrets.spacemaven_user }}" >> gradle.properties
          echo "spacemaven.key=${{ secrets.spacemaven_key }}" >> gradle.properties
      - name: Publish Project
        if: ${{ inputs.publish_spaceport }}
        run: ./gradlew publishCommonArtifactsToSpacemavenNativeRepository
