name: Build & Publish to Spacemaven Repository

on:
  workflow_dispatch:
    inputs:
      clear_cache:
        type: boolean
        default: false
        description: Clear the cache
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"

jobs:
  build-and-publish:
    uses: spacemaven-packages/spaceport/.github/workflows/spacemaven.yml@workflows
    permissions:
      # needed for clear_cache
      actions: write
    with:
      clear_cache: ${{ inputs.clear_cache || false }}
      publish_spaceport: false # TODO change to `true` when ready
